align_args: true
align_parameter: true
align_table_field: true
break_after_functioncall_lp: false
break_after_functiondef_lp: false
break_after_operator: false
break_after_table_lb: false
break_before_functioncall_rp: true
break_before_functiondef_rp: true
break_before_table_rb: false
chop_down_kv_table: true
chop_down_parameter: false
chop_down_table: true
column_limit: 120
column_table_limit: 100
continuation_indent_width: 2
double_quote_to_single_quote: true
extra_sep_at_table_end: false
indent_width: 2
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
line_breaks_after_function_body: 1
no_spaces_around_equals_in_field: true
single_quote_to_double_quote: false
spaces_around_equals_in_field: false
spaces_before_call: 0
tab_width: 2
table_sep: ','
use_tab: false

