-- Import Lua modules
require('core/lazy')
require('core/autocmds')
require('core/keymaps')
require('core/statusline')
require('core/options')
require('lsp/lspconfig')
require('plugins/neo-tree')
require('plugins/indent-blankline')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
