local g, o = vim.g, vim.o

g.mapleader = ' '
g.maplocalleader = ' '

g.loaded_2html_plugin = 1
g.loaded_fzf = 1
g.loaded_gzip = 1
g.loaded_matchit = 1
g.loaded_matchparen = 1
g.loaded_netrw = 1
g.loaded_netrwPlugin = 1
g.loaded_tar = 1
g.loaded_tarPlugin = 1
g.loaded_zipPlugin = 1

o.autowrite = true
o.background = 'dark'
o.clipboard = 'unnamedplus'
o.concealcursor = 'n'
o.conceallevel = 2
o.confirm = true
o.cursorline = true
o.expandtab = true
o.hidden = true
o.ignorecase = true
o.inccommand = 'split'
o.joinspaces = false
o.mouse = 'a'
o.number = true
o.pumblend = 10
o.pumheight = 10
o.scrolloff = 8
o.shiftround = true
o.shiftwidth = 4
o.showmode = false
o.sidescrolloff = 8
o.signcolumn = 'yes'
o.smartcase = true
o.smartindent = true
o.splitbelow = true
o.splitright = true
o.tabstop = 4
o.termguicolors = true
o.undofile = true
o.undolevels = 10000
o.updatetime = 200
