name: "format"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  linting:
    name: Format files
    runs-on: ubuntu-latest
    steps:

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -g *.lua -- .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (linting) formatting
          commit_options: "--cleanup=default --no-verify --signoff"
          skip_dirty_check: false
