name: linter

on:
  push:
    branches: [develop]

jobs:
  lint:

    name: lint
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v2

      - name: run linter
        uses: github/super-linter@v3
        env:
          VALIDATE_YAML: true
          VALIDATE_BASH_EXEC: true
          OUTPUT_FOLDER: super-linter.report
          OUTPUT_DETAILS: detailed
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

