name: "release"


    
on:
  workflow_run:
    workflows: ["format"]
    branches: [master]
    types: 
      - completed
      - requested
  workflow_dispatch:

  push:
    paths:
      - '**.md'
      - '**.yml'
      - '**.json'

jobs:

  on-success:
    runs-on: ubuntu-latest
    permissions: write-all


    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
     
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Resolve dependencies
        run: |
           npm install -D release-it \
                         @release-it/bumper \
                         @release-it/conventional-changelog
                
      - name: Publish release
        uses: TheRealWaldo/release-it@v0.5.0
        with:
          github-username: vladdoster
          git-user-name: vladdoster
          git-user-email: mvdoster@gmail.com
          no-increment: false
          json-opts: >
            {
                "config": '.github/release-it.json',
                "preRelease": 'beta'
            }

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Skip release
        run: |
          echo "Skipping release due to formatting workflow failure"
